# name: Update db json

# on:
#   schedule:
#     - cron: "0 14 * * *" # 2:00 PM UTC (10:00 AM ET)
#   workflow_dispatch:

# permissions:
#   contents: write

# jobs:
#   get-gifts:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#       - name: Set up Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: "npm"
#       - name: cd api
#         run: cd api
#       - name: Install dependencies
#         run: npm i
#       - name: Update trending json
#         run: npm run prod
#       - name: Commit and push
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           git config --global user.email "this.is.aditeya@gmail.com"
#           git config --global user.name "GH Action"
#           git add .
#           DATE=$(date +'%m.%d')
#           git diff --quiet && git diff --staged --quiet || (git commit -m "$DATE trending" && git push)